services:
  - type: web
    name: farmart-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python seed_db.py && gunicorn wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
